version: '3.8'

services:
  app:
    build:
      context: .
    container_name: catatin-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: catatin-backend
      DB_USERNAME: root
      DB_PASSWORD: root

  db:
    image: mysql:8
    container_name: catatin-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catatin-backend
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
